#!/bin/sh
set -eux
tar xf *
rm *.tar.gz
cd *
sh install.sh \
      --disable-ldconfig \
      --prefix="" \
      --destdir="$DESTDIR" \
      --components="rustc,cargo,rust-std-x86_64-unknown-linux-musl"